env:
  browser: true
  es6: true
extends:
  - airbnb-base
  - plugin:vue/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2018
  sourceType: module
plugins:
  - vue
rules: {}
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .vue
