stages:
  - install
  - test
  - build

variables:
  APP_ENV: "testing"

npm:dev:
  stage: install
  image: node:carbon-stretch
  script:
    - node -v && npm -v
    - npm install
  artifacts:
    expire_in: 25 mins
    paths:
      - node_modules
  only:
    - tags
    - web
    - merge_requests

tslint:
  stage: test
  image: node:carbon-stretch
  script:
    - npm run eslint
  dependencies:
    - npm:dev
  only:
    - tags
    - web
    - merge_requests

npm:build:
  stage: build
  image: node:carbon-stretch
  script:
    - sed -i "s/v0.0.0-placeholder/${CI_BUILD_REF_NAME:1}/g" manifest.json package.json
    - apt update && apt install zip
    - npm run production
    - ./cmd.sh release
    - ./cmd.sh source
  artifacts:
    expire_in: 1 day
    paths:
      - tabby.zip
      - tabby-source.zip
  dependencies:
    - npm:dev
  only:
    - tags
    - web

