version: "2"
services:
  node:
    environment:
      - npm_config_cache=/npm-cache
    build:
      context: ./docker
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - node-data:/npm-cache
volumes:
  node-data: